# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ac6cf886e6efc6b7e499146691f4bc366572779062d8720ddfc6970d141c1ba0b1e8a75042df4e65da14e6c2c579cc95979fb3c15db78ce9fd18143f4ea5372

test:
  secret_key_base: 5d3e7b680ef02e1ea634e387eb1d80ce9478fb5ebf694b1d8460d271baa548b29813db48125cc8733adb7a43b6670cc178fd10d77dafaf6d32f5366636eae6fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
